# Generated by Django 5.1.1 on 2024-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.PositiveIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
